development:
  cloud_name: espadaysantacruz
  api_key: '767115286582337'
  api_secret: lXblXH0XKMDbAB7gqaCgDQtet8s
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: espadaysantacruz
  api_key: '767115286582337'
  api_secret: lXblXH0XKMDbAB7gqaCgDQtet8s
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name:  <%= ENV['CLOUDINARY_NAME'] %>
  api_key:  <%= ENV['CLOUDINARY_KEY'] %>
  api_secret:  <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true