
production:
  KEEN_PROJECT_ID: <%= ENV['KEEN_PROJECT_ID'] %>
  KEEN_MASTER_KEY: <%= ENV['KEEN_MASTER_KEY'] %>
  KEEN_WRITE_KEY: <%= ENV['KEEN_WRITE_KEY'] %>
  KEEN_READ_KEY: <%= ENV['KEEN_READ_KEY'] %>