require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpecialLocationsController do

  # This should return the minimal set of attributes required to create a valid
  # SpecialLocation. As you add validations to SpecialLocation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpecialLocationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all special_locations as @special_locations" do
      special_location = SpecialLocation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:special_locations).should eq([special_location])
    end
  end

  describe "GET show" do
    it "assigns the requested special_location as @special_location" do
      special_location = SpecialLocation.create! valid_attributes
      get :show, {:id => special_location.to_param}, valid_session
      assigns(:special_location).should eq(special_location)
    end
  end

  describe "GET new" do
    it "assigns a new special_location as @special_location" do
      get :new, {}, valid_session
      assigns(:special_location).should be_a_new(SpecialLocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested special_location as @special_location" do
      special_location = SpecialLocation.create! valid_attributes
      get :edit, {:id => special_location.to_param}, valid_session
      assigns(:special_location).should eq(special_location)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpecialLocation" do
        expect {
          post :create, {:special_location => valid_attributes}, valid_session
        }.to change(SpecialLocation, :count).by(1)
      end

      it "assigns a newly created special_location as @special_location" do
        post :create, {:special_location => valid_attributes}, valid_session
        assigns(:special_location).should be_a(SpecialLocation)
        assigns(:special_location).should be_persisted
      end

      it "redirects to the created special_location" do
        post :create, {:special_location => valid_attributes}, valid_session
        response.should redirect_to(SpecialLocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved special_location as @special_location" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialLocation.any_instance.stub(:save).and_return(false)
        post :create, {:special_location => { "name" => "invalid value" }}, valid_session
        assigns(:special_location).should be_a_new(SpecialLocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialLocation.any_instance.stub(:save).and_return(false)
        post :create, {:special_location => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested special_location" do
        special_location = SpecialLocation.create! valid_attributes
        # Assuming there are no other special_locations in the database, this
        # specifies that the SpecialLocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpecialLocation.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => special_location.to_param, :special_location => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested special_location as @special_location" do
        special_location = SpecialLocation.create! valid_attributes
        put :update, {:id => special_location.to_param, :special_location => valid_attributes}, valid_session
        assigns(:special_location).should eq(special_location)
      end

      it "redirects to the special_location" do
        special_location = SpecialLocation.create! valid_attributes
        put :update, {:id => special_location.to_param, :special_location => valid_attributes}, valid_session
        response.should redirect_to(special_location)
      end
    end

    describe "with invalid params" do
      it "assigns the special_location as @special_location" do
        special_location = SpecialLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_location.to_param, :special_location => { "name" => "invalid value" }}, valid_session
        assigns(:special_location).should eq(special_location)
      end

      it "re-renders the 'edit' template" do
        special_location = SpecialLocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpecialLocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => special_location.to_param, :special_location => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested special_location" do
      special_location = SpecialLocation.create! valid_attributes
      expect {
        delete :destroy, {:id => special_location.to_param}, valid_session
      }.to change(SpecialLocation, :count).by(-1)
    end

    it "redirects to the special_locations list" do
      special_location = SpecialLocation.create! valid_attributes
      delete :destroy, {:id => special_location.to_param}, valid_session
      response.should redirect_to(special_locations_url)
    end
  end

end
